export const GAME_TAG_LABELS = {
  PVP: "PvP",
  COOP: "협동",
  TEAM: "팀 플레이",
  COMPETITIVE: "경쟁전",
  CASUAL: "캐주얼",
  SURVIVAL: "생존",
  BATTLE_ROYALE: "배틀로얄",
  FPS: "FPS",
  MMORPG: "MMORPG",
  MOBA: "MOBA",
  TPS: "TPS",
  SPORTS: "스포츠",
  PARTY: "파티",
  STRATEGY: "전략",
  PUZZLE: "퍼즐",
  HORROR: "호러",
  SANDBOX: "샌드박스",
  RAID: "레이드",
  OPEN_WORLD: "오픈월드",
};
