const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  let signupCalls = 0;
  let expire = false;
  let failRestore = false;
  await page.route('**/api/auth/**', async route => {
    const request = route.request();
    const path = new URL(request.url()).pathname;
    let status = 200;
    let body;
    if (path.endsWith('/signup')) {
      signupCalls++;
      const data = request.postDataJSON();
      assert.deepEqual(data, {loginId:'tester_123',password:'pass1234',nickname:'테스트유저', ...(signupCalls > 1 ? {sajuInput:{birthDate:'2000-01-02',gender:'FEMALE',calendarType:'LUNAR',birthTimeBranch:'UNKNOWN'}} : {})});
      status = signupCalls === 1 ? 409 : 201;
      body = signupCalls === 1 ? {message:'이미 사용 중인 아이디입니다.'} : {userId:1};
    } else if (path.endsWith('/login')) {
      assert.equal(request.headers().authorization, undefined);
      const data = request.postDataJSON();
      status = data.password === 'wrongpass' ? 401 : 200;
      body = status === 401 ? {} : {tokenType:'Bearer',accessToken:'test-token',expiresIn:3600,user:{userId:1,loginId:'tester_123',nickname:'테스트유저',role:'USER'}};
    } else if (path.endsWith('/me')) {
      assert.equal(request.headers().authorization, 'Bearer test-token');
      status = expire ? 401 : failRestore ? 503 : 200;
      body = status === 200 ? {userId:1,loginId:'tester_123',nickname:'테스트유저',role:'USER'} : {};
    } else throw new Error(path);
    await route.fulfill({status, contentType:'application/json', body:JSON.stringify(body)});
  });
  const origin = process.env.TEST_BASE_URL || 'http://127.0.0.1:5173';
  await page.goto(origin+'/mypage');
  await page.waitForURL('**/login');
  await page.getByRole('button',{name:'회원가입',exact:true}).first().click();
  await page.waitForURL('**/signup');
  await page.getByLabel('아이디', {exact:true}).fill('test@email.com');
  assert.equal(await page.locator('#loginId').evaluate(el => el.checkValidity()), false);
  await page.getByLabel('아이디',{exact:true}).fill('tester_123');
  await page.getByLabel('닉네임',{exact:true}).fill('테스트유저');
  await page.getByLabel('비밀번호',{exact:true}).fill('pass1234');
  await page.getByLabel('비밀번호 확인',{exact:true}).fill('different');
  await page.locator('button[type=submit]').click();
  await page.getByRole('alert').filter({hasText:'일치하지'}).waitFor();
  assert.equal(signupCalls,0);
  await page.getByLabel('비밀번호 확인',{exact:true}).fill('pass1234');
  await page.locator('button[type=submit]').click();
  await page.getByRole('alert').filter({hasText:'이미 사용'}).waitFor();
  assert.equal(await page.locator('#birthTimeBranch option').count(),13);
  await page.getByLabel('생년월일',{exact:true}).fill('2000-01-02');
  await page.locator('button[type=submit]').click();
  await page.getByRole('alert').filter({hasText:'함께 선택'}).waitFor();
  assert.equal(signupCalls,1);
  await page.getByRole('button',{name:'사주 입력 초기화'}).click();
  assert.equal(await page.locator('#birthDate').inputValue(),'');
  await page.getByLabel('생년월일',{exact:true}).fill('2000-01-02');
  await page.getByLabel('성별',{exact:true}).selectOption('FEMALE');
  await page.getByLabel('양력 / 음력',{exact:true}).selectOption('LUNAR');
  await page.locator('button[type=submit]').click();
  await page.getByRole('status').filter({hasText:'회원가입이 완료'}).waitFor();
  assert.equal(new URL(page.url()).pathname, '/login');
  await page.getByLabel('비밀번호',{exact:true}).fill('wrongpass');
  await page.locator('button[type=submit]').click();
  await page.getByRole('alert').filter({hasText:'올바르지'}).waitFor();
  await page.getByLabel('비밀번호',{exact:true}).fill('pass1234');
  await page.locator('button[type=submit]').click();
  await page.waitForURL(url => url.pathname !== '/login');
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('guildhub.accessToken')),'test-token');
  await page.reload();
  await page.getByRole('button',{name:'로그아웃',exact:true}).waitFor();
  failRestore = true;
  await page.reload();
  await page.getByRole('button',{name:'다시 시도'}).waitFor();
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('guildhub.accessToken')),'test-token');
  failRestore = false;
  await page.getByRole('button',{name:'다시 시도'}).click();
  await page.getByRole('button',{name:'로그아웃',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.locator('nav > button.md\\:hidden').click();
  await page.getByRole('button',{name:'로그아웃',exact:true}).last().click();
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('guildhub.accessToken')),null);
  await page.goto(origin+'/login');
  await page.getByLabel('아이디',{exact:true}).fill('tester_123');
  await page.getByLabel('비밀번호',{exact:true}).fill('pass1234');
  await page.locator('button[type=submit]').click();
  await page.waitForURL(url => url.pathname === '/' || url.pathname === '/mypage');
  expire = true;
  await page.goto(origin+'/mypage');
  await page.waitForURL('**/login');
  await page.getByRole('status').filter({hasText:'만료'}).waitFor();
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('guildhub.accessToken')),null);
  assert.deepEqual(errors,[]);
  console.log('PASS: Optional saju omission, partial input, reset, 13 birth times, saju payload, ID validation, signup, login, reload, retry, logout, expiration.');
  await browser.close();
})().catch(error=>{ console.error(error); process.exit(1); });
